// Rewrite the instructions in your own words
/* should return the string +3 position of any letter in the string

*/

// Write the objectives and the tests

// Write the pseudocode
/*Basically i used javasript not blockly
I created a function with one parameter str
a variable slov which is empty string
a ascci variable to store the number for example A = 65


*/


// paste your JS generated by blockly below here
function cesar3(str){
    var solv = "";
    for(var i = 0; i < str.length; i++){
       var ascci = str[i].charCodeAt();//ascii is American standard code for information interchange A = 65;
       if(ascci >= 65 && ascci <= 87){
           solv += String.fromCharCode(ascci + 3);
       }else if(ascci >= 88 && ascci <= 90){
           solv += String.fromCharCode(ascci - 23);
       }else{
           solv += str[i];
       }


    }
    return solv;

}
console.log(cesar3("XYZ"));